---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorwebidentity
  namespace: multiapp

  labels:
    app: blazorwebidentity
spec:
  minReadySeconds: 60
  replicas: 2
  selector:
    matchLabels:
      app: blazorwebidentity
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blazorwebidentity
    spec:
      containers:
      - name: blazorwebidentity
        image: nguyenvantu/blazorwebidentity:493d5f1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: blazorwebidentity-env
      terminationGracePeriodSeconds: 180
