name: Web Identity Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create temporary NuGet config
      run: |
        mkdir -p ./temp-nuget
        cat <<EOF > ./temp-nuget/nuget.config
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="github" value="https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
          </packageSources>
          <packageSourceCredentials>
            <github>
              <add key="Username" value="${{ github.repository_owner }}" />
              <add key="ClearTextPassword" value="${{ secrets.LIB_TOKEN }}" />
            </github>
          </packageSourceCredentials>
        </configuration>
        EOF

    - name: Build container image
      run: |
        docker build \
          --build-arg NUGET_CONFIG=./temp-nuget/nuget.config \
          -f IdentityAuthen/Dockerfile \
          -t blazorwebidentity:$(echo $GITHUB_SHA | head -c7) .

    - name: Tag image  
      run: |
        docker tag blazorwebidentity:$(echo $GITHUB_SHA | head -c7) \
        nguyenvantu/blazorwebidentity:$(echo $GITHUB_SHA | head -c7)

    - name: Push image to Docker Hub
      run: docker push nguyenvantu/blazorwebidentity:$(echo $GITHUB_SHA | head -c7)

    - name: Update deployment file
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        sed -i 's|nguyenvantu/blazorwebidentity:.*|nguyenvantu/blazorwebidentity:'${TAG}'|' IdentityAuthen/WebApplication1/aspirate-output/blazorwebidentity/deployment.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -k Authen/aspirate-output/blazorwebidentity/.
